// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdtuWsntirU6Eh7TiFO93BCSq9bpDbjPA',
    appId: '1:817899666782:web:96fa572f0cfda3296ae3cf',
    messagingSenderId: '817899666782',
    projectId: 'toastea-eeb58',
    authDomain: 'toastea-eeb58.firebaseapp.com',
    storageBucket: 'toastea-eeb58.appspot.com',
    measurementId: 'G-74JCRLE1SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTPSszdFq5rfAoWzi63POeM-TQ9iBBOs',
    appId: '1:817899666782:android:2d021465f640acdb6ae3cf',
    messagingSenderId: '817899666782',
    projectId: 'toastea-eeb58',
    storageBucket: 'toastea-eeb58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGvSPo2lh29mdmKGoAJ7wdNnOBK_girg',
    appId: '1:817899666782:ios:7c88866bb9f360636ae3cf',
    messagingSenderId: '817899666782',
    projectId: 'toastea-eeb58',
    storageBucket: 'toastea-eeb58.appspot.com',
    iosClientId: '817899666782-s4dmu2jgk6nerp6ha8no0k35bin23s1h.apps.googleusercontent.com',
    iosBundleId: 'com.kaskadegroup.src',
  );
}
